### ISSUE TITLE
Question about the supervised task learning part

### ISSUE THREAD

**Issue by cpuyyp** [Prasanna1991/IBP-VAE#2]
Hi, 

I am just curious how is the supervised part implemented? The cIBP-VAE in the paper

Or this repo is purely for the unsupervised part?

Thanks!!

**Comment by Prasanna1991** [comment]
Yes, the repo, unfortunately, is only for the unsupervised part. The cIBP-VAE extension should be straight-forward. Please let me know (email: pkg2182@rit.edu) if you want any help on that. 

Best,
Prashnna
